# EDA

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [19]:
# Load dataset
df = pd.read_csv("car data.csv")

In [3]:
df

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0       ritz  2014           3.35           5.59       27000    Petrol   
1        sx4  2013           4.75           9.54       43000    Diesel   
2       ciaz  2017           7.25           9.85        6900    Petrol   
3    wagon r  2011           2.85           4.15        5200    Petrol   
4      swift  2014           4.60           6.87       42450    Diesel   
..       ...   ...            ...            ...         ...       ...   
296     city  2016           9.50          11.60       33988    Diesel   
297     brio  2015           4.00           5.90       60000    Petrol   
298     city  2009           3.35          11.00       87934    Petrol   
299     city  2017          11.50          12.50        9000    Diesel   
300     brio  2016           5.30           5.90        5464    Petrol   

    Seller_Type Transmission  Owner  
0        Dealer       Manual      0  
1        Dealer       Manual      0  
2        Dealer       Manual      0  
3        Dealer       Manual      0  
4        Dealer       Manual      0  
..          ...          ...    ...  
296      Dealer       Manual      0  
297      Dealer       Manual      0  
298      Dealer       Manual      0  
299      Dealer       Manual      0  
300      Dealer       Manual      0  

[301 rows x 9 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Car_Name       301 non-null    object 
 1   Year           301 non-null    int64  
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Kms_Driven     301 non-null    int64  
 5   Fuel_Type      301 non-null    object 
 6   Seller_Type    301 non-null    object 
 7   Transmission   301 non-null    object 
 8   Owner          301 non-null    int64  
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB


In [20]:
df["age"] = df["Year"].apply(lambda x: 2024 - x)

In [21]:
df.drop("Year",axis=1,inplace=True)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Car_Name       301 non-null    object 
 1   Selling_Price  301 non-null    float64
 2   Present_Price  301 non-null    float64
 3   Kms_Driven     301 non-null    int64  
 4   Fuel_Type      301 non-null    object 
 5   Seller_Type    301 non-null    object 
 6   Transmission   301 non-null    object 
 7   Owner          301 non-null    int64  
 8   age            301 non-null    int64  
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB


In [25]:
df.drop("Car_Name",axis=1,inplace=True)

In [26]:
df.duplicated().sum()

2

In [28]:
df.drop_duplicates(inplace=True)

In [29]:
df.duplicated().sum()

0

In [30]:
df.describe()

Selling_Price  Present_Price     Kms_Driven       Owner         age
count     299.000000     299.000000     299.000000  299.000000  299.000000
mean        4.589632       7.541037   36916.752508    0.043478   10.384615
std         4.984240       8.567887   39015.170352    0.248720    2.896868
min         0.100000       0.320000     500.000000    0.000000    6.000000
25%         0.850000       1.200000   15000.000000    0.000000    8.000000
50%         3.510000       6.100000   32000.000000    0.000000   10.000000
75%         6.000000       9.840000   48883.500000    0.000000   12.000000
max        35.000000      92.600000  500000.000000    3.000000   21.000000

In [31]:
df.Fuel_Type.value_counts()

Petrol    239
Diesel     58
CNG         2
Name: Fuel_Type, dtype: int64

In [38]:
df = df[df["Fuel_Type"]!="CNG"]

In [39]:
df

Selling_Price  Present_Price  Kms_Driven Fuel_Type Seller_Type  \
0             3.35           5.59       27000    Petrol      Dealer   
1             4.75           9.54       43000    Diesel      Dealer   
2             7.25           9.85        6900    Petrol      Dealer   
3             2.85           4.15        5200    Petrol      Dealer   
4             4.60           6.87       42450    Diesel      Dealer   
..             ...            ...         ...       ...         ...   
296           9.50          11.60       33988    Diesel      Dealer   
297           4.00           5.90       60000    Petrol      Dealer   
298           3.35          11.00       87934    Petrol      Dealer   
299          11.50          12.50        9000    Diesel      Dealer   
300           5.30           5.90        5464    Petrol      Dealer   

    Transmission  Owner  age  
0         Manual      0   10  
1         Manual      0   11  
2         Manual      0    7  
3         Manual      0   13  
4         Manual      0   10  
..           ...    ...  ...  
296       Manual      0    8  
297       Manual      0    9  
298       Manual      0   15  
299       Manual      0    7  
300       Manual      0    8  

[297 rows x 8 columns]

In [40]:
df.Fuel_Type.value_counts()

Petrol    239
Diesel     58
Name: Fuel_Type, dtype: int64

In [42]:
df.corr()

Selling_Price  Present_Price  Kms_Driven     Owner       age
Selling_Price       1.000000       0.876533    0.028919 -0.088269 -0.234283
Present_Price       0.876533       1.000000    0.205261  0.009794  0.053135
Kms_Driven          0.028919       0.205261    1.000000  0.089570  0.525661
Owner              -0.088269       0.009794    0.089570  1.000000  0.182228
age                -0.234283       0.053135    0.525661  0.182228  1.000000

In [46]:
df = pd.get_dummies(df,drop_first=True,dtype="int64")

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 297 entries, 0 to 300
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Selling_Price           297 non-null    float64
 1   Present_Price           297 non-null    float64
 2   Kms_Driven              297 non-null    int64  
 3   Owner                   297 non-null    int64  
 4   age                     297 non-null    int64  
 5   Fuel_Type_Petrol        297 non-null    int64  
 6   Seller_Type_Individual  297 non-null    int64  
 7   Transmission_Manual     297 non-null    int64  
dtypes: float64(2), int64(6)
memory usage: 20.9 KB


In [49]:
X = df.drop("Selling_Price",axis=1)
Y = df.Selling_Price

In [52]:
# RFE Method
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression
model = LinearRegression()
rfe = RFE(model)
fit  = rfe.fit(X,Y)

In [54]:
fit.n_features_

3

In [55]:
fit.ranking_

array([4, 5, 3, 2, 1, 1, 1])

In [56]:
fit.support_

array([False, False, False, False,  True,  True,  True])

In [57]:
X.columns

Index(['Present_Price', 'Kms_Driven', 'Owner', 'age', 'Fuel_Type_Petrol',
       'Seller_Type_Individual', 'Transmission_Manual'],
      dtype='object')

In [59]:
from sklearn.tree import DecisionTreeRegressor
model = DecisionTreeRegressor()
model.fit(X,Y)

DecisionTreeRegressor()

In [65]:
(model.feature_importances_)

array([8.90556710e-01, 1.78543845e-02, 4.51850032e-05, 8.40468980e-02,
       7.04337639e-03, 7.43271715e-05, 3.79118616e-04])

In [66]:
import ppscore as pps

In [68]:
pp_score = pps.matrix(df)

In [72]:
pp_score = pp_score[["x","y","ppscore"]]

In [74]:
pp_score = pp_score[pp_score["y"]=="Selling_Price"]

In [77]:
pp_score.sort_values(by="ppscore",ascending=False)

x              y   ppscore
0            Selling_Price  Selling_Price  1.000000
8            Present_Price  Selling_Price  0.555254
48  Seller_Type_Individual  Selling_Price  0.285163
40        Fuel_Type_Petrol  Selling_Price  0.082623
16              Kms_Driven  Selling_Price  0.000000
24                   Owner  Selling_Price  0.000000
32                     age  Selling_Price  0.000000
56     Transmission_Manual  Selling_Price  0.000000

In [78]:
X = df[["Present_Price","Seller_Type_Individual","Fuel_Type_Petrol","age"]]

In [79]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 297 entries, 0 to 300
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Present_Price           297 non-null    float64
 1   Seller_Type_Individual  297 non-null    int64  
 2   Fuel_Type_Petrol        297 non-null    int64  
 3   age                     297 non-null    int64  
dtypes: float64(1), int64(3)
memory usage: 11.6 KB


In [81]:
Y = df.Selling_Price

In [82]:
cleaned_data = pd.concat([X,Y],axis=1)

In [83]:
cleaned_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 297 entries, 0 to 300
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Present_Price           297 non-null    float64
 1   Seller_Type_Individual  297 non-null    int64  
 2   Fuel_Type_Petrol        297 non-null    int64  
 3   age                     297 non-null    int64  
 4   Selling_Price           297 non-null    float64
dtypes: float64(2), int64(3)
memory usage: 13.9 KB


In [84]:
cleaned_data.duplicated().sum()

4

In [85]:
cleaned_data.drop_duplicates(inplace=True)

In [86]:
cleaned_data.duplicated().sum()

0

In [87]:
cleaned_data.to_csv("cleaned_dataset.csv")